# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37b6c1a08bb38ec46c1b566459c2a5b19e6fcfc760fd36aa00ad51ae91468a1493a9ff27ae65abcfc02b1fe5446372587a77be7ccc8ee9c29dad014f50f7b93f

test:
  secret_key_base: 3b008cd80e76518c393bca0d9156f3b4351c115020e2846de4d6322e73121a7ff4642de83aa3f159febd647422ec9503c0a48bff038370f5219636d1bb08a3de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
